version: "3"

services:
   web:
      build: .
      command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
      volumes:
         - .:/app
      ports:
         - "8000:8000"
      depends_on:
         - my_postgres
      environment:
         - SECRET_KEY: ${ secrets.SECRET_KEY }
         - POSTGRES_DB: ${ secrets.POSTGRES_NAME }
         - POSTGRES_NAME: ${ secrets.POSTGRES_NAME }
         - POSTGRES_USER: ${ secrets.POSTGRES_USER }
         - POSTGRES_PASSWORD: ${ secrets.POSTGRES_PASSWORD }
         - POSTGRES_HOST: ${ secrets.POSTGRES_HOST }
         - POSTGRES_PORT: ${ secrets.POSTGRES_PORT }

   my_postgres:
      image: postgres
      environment:
         - POSTGRES_DB=${POSTGRES_NAME}
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # env_file:
      #    - .env
