version: "3"

services:
   db:
      image: postgres
      environment:
         POSTGRES_NAME: $POSTGRES_NAME
         POSTGRES_USER: $POSTGRES_USER
         POSTGRES_PASSWORD: $POSTGRES_PASSWORD

   web:
      build: .
      volumes:
         - .:/usr/src/app
      ports:
         - "8000:8000"
      depends_on:
         - db
      environment:
         SECRET_KEY: $SECRET_KEY
         POSTGRES_USER: $POSTGRES_USER
         POSTGRES_PASSWORD: $POSTGRES_PASSWORD
         POSTGRES_NAME: $POSTGRES_NAME
