version: "3"

services:
   my_postgres:
      image: postgres:latest
      ports:
         - "5432:5432"
      environment:
         - POSTGRES_DB=${POSTGRES_NAME}
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_HOST=${POSTGRES_HOST}
      # env_file:
      #    - .env

   web:
      build: .
      volumes:
         - .:/app
      ports:
         - "8000:8000"
      depends_on:
         - my_postgres
      # env_file:
      #    - .env
      environment:
         SECRET_KEY: ${SECRET_KEY}
         POSTGRES_DB: ${POSTGRES_DB}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_PORT: ${POSTGRES_PORT}
         POSTGRES_HOST: my_postgres
