
# register user
POST http://127.0.0.1:8000/user/register/
Content-Type: application/json

{
    "username": "username",
    "password": "Password",
    "first_name": "first_name",
    "last_name": "last_name",
    "email": "email@example.com"
}

###
# access token
POST http://127.0.0.1:8000/user/api/token/
Content-Type: application/json

{
    "username": "",
    "password": ""
}

###
# refresh token
# access token valid only for 5 minutes
POST http://127.0.0.1:8000/user/api/token/refresh/
Content-Type: application/json

{
    "refresh": ""
}

###
# gets current user's data
GET http://127.0.0.1:8000/user/me/
Content-Type: application/json
Authorization: Bearer <your-token>

###
# update personal data
PUT http://127.0.0.1:8000/user/me/
Content-Type: application/json
Authorization: Bearer <your-token>

{
    "username": "foo",
    "first_name": "ccbcc",
    "last_name": "aaa",
    "email": "emu@example.com",

    "old_password": "only if neccessary",
    "new_password": "only if neccessary",
}

###
# get user with ID
GET http://127.0.0.1:8000/user/user/e32ad9a0-88ab-49cf-8654-05aa073858fb
Content-Type: application/json
Authorization: Bearer <your-token>

###
# post meal
POST http://127.0.0.1:8000/recipes/add/
Content-Type: application/json
Authorization: Bearer <your-token>

{
    "strCategory": "Vegan",
    "strMeal": "Beef Meal",
    "strDrinkAlternate": "",
    "strArea": "",
    "strInstructions": "Cook the beef...",
    "strMealThumb": "",
    "strTags": "",
    "strYoutube": "",
    "strIngredient1": "Beef",
    "strIngredient2": "", 
    "strIngredient3": "", 
    "strIngredient4": "", 
    "strIngredient5": "", 
    "strIngredient6": "", 
    "strIngredient7": "", 
    "strIngredient8": "", 
    "strIngredient9": "", 
    "strIngredient10": "", 
    "strIngredient11": "", 
    "strIngredient12": "", 
    "strIngredient13": "", 
    "strIngredient14": "", 
    "strIngredient15": "", 
    "strIngredient16": "", 
    "strIngredient17": "", 
    "strIngredient18": "", 
    "strIngredient19": "", 
    "strIngredient20": "", 
    "strMeasure1": "1 lb",
    "strMeasure2": "", 
    "strMeasure3": "", 
    "strMeasure4": "", 
    "strMeasure5": "", 
    "strMeasure6": "", 
    "strMeasure7": "", 
    "strMeasure8": "", 
    "strMeasure9": "", 
    "strMeasure10": "", 
    "strMeasure11": "", 
    "strMeasure12": "", 
    "strMeasure13": "", 
    "strMeasure14": "", 
    "strMeasure15": "", 
    "strMeasure16": "", 
    "strMeasure17": "", 
    "strMeasure18": "", 
    "strMeasure19": "", 
    "strMeasure20": "", 
    "strSource": "",
    "strImageSource": "",
    "strCreativeCommonsConfirmed": false,
    "dateModified": "2024-07-26T22:22:12Z"
}

