# Generated by Django 5.0.7 on 2024-08-05 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strCategory', models.CharField(max_length=64)),
                ('strCategoryTumb', models.URLField(max_length=300)),
                ('strCategoryDescription', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('idMeal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strMeal', models.CharField(max_length=200)),
                ('strDrinkAlternate', models.CharField(blank=True, max_length=64, null=True)),
                ('strArea', models.CharField(blank=True, max_length=64)),
                ('strInstructions', models.TextField(max_length=5000)),
                ('strMealThumb', models.URLField(blank=True)),
                ('strTags', models.CharField(blank=True, max_length=200)),
                ('strYoutube', models.URLField(blank=True)),
                ('strIngredient1', models.CharField(blank=True, max_length=64)),
                ('strIngredient2', models.CharField(blank=True, max_length=64)),
                ('strIngredient3', models.CharField(blank=True, max_length=64)),
                ('strIngredient4', models.CharField(blank=True, max_length=64)),
                ('strIngredient5', models.CharField(blank=True, max_length=64)),
                ('strIngredient6', models.CharField(blank=True, max_length=64)),
                ('strIngredient7', models.CharField(blank=True, max_length=64)),
                ('strIngredient8', models.CharField(blank=True, max_length=64)),
                ('strIngredient9', models.CharField(blank=True, max_length=64)),
                ('strIngredient10', models.CharField(blank=True, max_length=64)),
                ('strIngredient11', models.CharField(blank=True, max_length=64)),
                ('strIngredient12', models.CharField(blank=True, max_length=64)),
                ('strIngredient13', models.CharField(blank=True, max_length=64)),
                ('strIngredient14', models.CharField(blank=True, max_length=64)),
                ('strIngredient15', models.CharField(blank=True, max_length=64)),
                ('strIngredient16', models.CharField(blank=True, max_length=64)),
                ('strIngredient17', models.CharField(blank=True, max_length=64)),
                ('strIngredient18', models.CharField(blank=True, max_length=64)),
                ('strIngredient19', models.CharField(blank=True, max_length=64)),
                ('strIngredient20', models.CharField(blank=True, max_length=64)),
                ('strMeasure1', models.CharField(blank=True, max_length=60)),
                ('strMeasure2', models.CharField(blank=True, max_length=60)),
                ('strMeasure3', models.CharField(blank=True, max_length=60)),
                ('strMeasure4', models.CharField(blank=True, max_length=60)),
                ('strMeasure5', models.CharField(blank=True, max_length=60)),
                ('strMeasure6', models.CharField(blank=True, max_length=60)),
                ('strMeasure7', models.CharField(blank=True, max_length=60)),
                ('strMeasure8', models.CharField(blank=True, max_length=60)),
                ('strMeasure9', models.CharField(blank=True, max_length=60)),
                ('strMeasure10', models.CharField(blank=True, max_length=60)),
                ('strMeasure11', models.CharField(blank=True, max_length=60)),
                ('strMeasure12', models.CharField(blank=True, max_length=60)),
                ('strMeasure13', models.CharField(blank=True, max_length=60)),
                ('strMeasure14', models.CharField(blank=True, max_length=60)),
                ('strMeasure15', models.CharField(blank=True, max_length=60)),
                ('strMeasure16', models.CharField(blank=True, max_length=60)),
                ('strMeasure17', models.CharField(blank=True, max_length=60)),
                ('strMeasure18', models.CharField(blank=True, max_length=60)),
                ('strMeasure19', models.CharField(blank=True, max_length=60)),
                ('strMeasure20', models.CharField(blank=True, max_length=60)),
                ('strSource', models.URLField(blank=True)),
                ('strImageSource', models.URLField(blank=True)),
                ('strCreativeCommonsConfirmed', models.BooleanField(blank=True, null=True)),
                ('dateModified', models.DateTimeField(blank=True, null=True)),
                ('strCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
