# Generated by Django 5.0.7 on 2024-07-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='strTags',
        ),
        migrations.AddField(
            model_name='meal',
            name='strTags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
