# Generated by Django 5.0.7 on 2024-07-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='strCreativeCommonsConfirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
