# Generated by Django 5.0.7 on 2024-07-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_meal_strtags_meal_strtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='dateModified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
