# Generated by Django 5.0.7 on 2024-07-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_meal_datemodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='strInstructions',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure10',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure11',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure12',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure13',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure14',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure15',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure16',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure17',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure18',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure19',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure20',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure3',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure4',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure5',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure6',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure7',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure8',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meal',
            name='strMeasure9',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
