# Generated by Django 5.0.7 on 2024-07-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='strCategoryTumb',
            field=models.URLField(max_length=300),
        ),
    ]
