name: Testing
on: push

jobs:
   test_project:
      runs-on: ubuntu-latest
      env:
         SECRET_KEY: ${{ secrets.SECRET_KEY }}
      steps:
         - uses: actions/checkout@v2
         - name: Set up Python
           uses: actions/setup-python@v2
           with:
              python-version: "3.12"
         - name: Install dependencies
           run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
         - name: Run Django unit tests
           run: |
              python3 manage.py test
