name: Testing
on: push

jobs:
   test_project:
      runs-on: ubuntu-latest
      env:
         SECRET_KEY: ${{ secrets.SECRET_KEY }}
         POSTGRES_DB: ${{ secrets.POSTGRES_NAME }}
         POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
         POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
         POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
         POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

      steps:
         - uses: actions/checkout@v4

         - name: Set up Python
           uses: actions/setup-python@v2
           with:
              python-version: "3.12"

         # - name: Run docker-compose
         #   run: docker-compose up -d

         - name: Install dependencies
           run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

         # https://github.com/marketplace/actions/action-docker-compose
         - name: Run docker compose
           uses: sudo-bot/action-docker-compose@latest
           with:
              # https://docs.docker.com/compose/reference/overview/
              cli-args: up -d
           env:
              POSTGRES_DB: ${{ secrets.POSTGRES_NAME }}
              POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
              POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
              POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
              POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
              POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}

         - name: Run Django unit tests
           run: |
              python3 manage.py test
